config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "posts#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
  devise_for :users
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :edit, :update]
  end
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :show, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commenter, class_name: 'User', foreign_key: :user_id
  belongs_to :post
  has_many :notifications, as: :notifiable

  validates_presence_of :body

  after_create :create_notification_for_author_and_commenters

  private

  def create_notification_for_author_and_commenters
    notification_body = "#{commenter.email} commented post: #{post.content.truncate(37)}"
    post.author_and_commenters_ids.each do |user_to_notify_id|
      next if user_to_notify_id == commenter.id

      Notification.create(body: notification_body,
                          link: "/posts/#{post.id}",
                          recipient_id: user_to_notify_id,
                          notifiable: self)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post), notice: 'Comment created successfully!'
    else
      flash[:comment_errors] = @comment.errors.full_messages
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_back fallback_location: root_path, notice: 'Comment deleted successfully!'
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def set_comment
    return if (@comment = Comment.find_by_id(params[:id]))

    redirect_back fallback_location: root_path, alert: 'Sorry, comment not found!'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="mb-2 border-bottom">
  <%= link_to comment.commenter.email, user_path(comment.commenter), class: 'fs-4  link-primary' %>
  <span class="fs-5">commented:</span>

  <p><%= comment.body %></p>

  <% if comment.commenter == current_user %> 
    <%= button_to comment_path(comment), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'mb-1 btn btn-sm btn-danger'  do %>
    Delete comment <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-recycle" viewBox="0 0 14 20">
    <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
  </svg>
    <% end %> 
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: Comment.new do |form| %>
  <%= form.hidden_field :post_id, value: post.id %>
  <%= form.label :body, 'Your new comment', class: 'form-label fs-5 text-decoration-underline' %>
  <%= form.text_area :body, class: 'form-control' %>
    <% if flash[:comment_errors] %>
          <% flash[:comment_errors].each do |error| %>
            <p class="mt-2 alert alert-danger"><%= error %></p>
          <% end %>
    <% end %>
  <%= form.submit class: "my-2 btn btn-success" %> 
<% end %>