config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "posts#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
  devise_for :users
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :edit, :update]
  end
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :show, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: 'is invalid' }

  has_many :friendships, ->(user) { sent_and_received(user.id) }, inverse_of: :user, dependent: :destroy
  has_many :accepted_friendships, ->(user) { sent_and_received(user.id).accepted }, class_name: 'Friendship'

  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile, dependent: :destroy

  after_create { Profile.create(user: self) }

  after_create { UserMailer.welcome_email(self).deliver_now } unless Rails.env.production? 

  def friends
    User.where.not(id: id).where(id: user_and_friends_ids)
  end

  def user_and_friends_posts
    Post.where(author: user_and_friends_ids).order(created_at: :DESC)
  end

  private

  def user_and_friends_ids
    return id if accepted_friendships.empty?

    accepted_friendships.pluck(:user_id, :friend_id).flatten
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    @pagy, @users = pagy(User.where.not(id: current_user.id), items: 9)
    @friendships = current_user.friendships
  end

  def show
    @posts = @user.posts.includes(:author, comments: :commenter).with_attached_images.order(created_at: :DESC)
    @plucked_likes_and_posts_ids_of_user_likes = current_user.likes.pluck(:id, :post_id)
    @friendship = current_user.friendships.where('user_id = :show_user_id OR friend_id = :show_user_id', show_user_id: @user.id ).take
  end

  private

  def set_user
    return if (@user = User.find_by_id(params[:id]))

    redirect_to users_path, alert: 'Sorry, user not found! Try again'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notification.html.erb
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  Notifications<span class="ms-1 badge bg-primary"><%= @current_user_unread_notifications_count %></span>
</a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <% @current_user_notifications.each do |notification| %>
        <li>
          <a class="dropdown-item <%= 'bg-success text-light' unless notification.read %>" href="<%= notification.link %>">
            <%= notification.body %>
          </a>
        </li>
    <% end %>
  </ul>

app/views/users/_other_user.html.erb
<li>
  <p>
    <%= other_user.email %>
    <% if (friendship = @friendships.find { |f| [current_user.id, other_user.id, f.user_id, f.friend_id].uniq.size == 2 }) %>
      <% if friendship.accepted? %>
       <%= form_with model: friendship, method: :delete do |form| %>
         <strong>Friend</strong>
         <%= form.submit 'Delete friend' %>
        <% end %>
      <% else %>
        <% if should_accept = friendship.friend_id == current_user.id  %>
          <%= form_with model: friendship do |form| %>
            <%= form.submit 'Accept request' %>
          <% end %>
        <% end %>
        <%= form_with model: friendship, method: :delete do |form| %>
          <%= form.submit should_accept ? 'Decline request' : 'Cancel request' %>
        <% end %>
      <% end %>
    <% else %>
      <%= form_with model: Friendship.new do |form| %>
        <%= form.hidden_field :friend_id, value: other_user.id %>
        <%= form.submit 'Add friend' %>
      <% end %>
    <% end %>
  </p>
</li>

app/views/users/_user.html.erb
<div class="col">
<div class="card mb-3 h-100" >
  <div class="row g-0 text-center my-auto">
    <div class="col-md-5 align-self-center ps-2">
        <% user_photo_or_default = (user.profile.photo.attached? ? user.profile.photo : "/assets/default_profile_photo.png" ) %>
      <%= image_tag user_photo_or_default, width: '200px', class: 'img-fluid rounded-circle mx-auto my-auto', alt: 'profile photo' %>
    </div>
    <div class="col-md-7">
      <div class="card-body">
        <h5 class="card-title"><%= link_to user.email, user_path(user) %></h5>
         <span>
            <% if (friendship = @friendships.find { |f| [current_user.id, user.id, f.user_id, f.friend_id].uniq.size == 2 }) %>
              <% if friendship.accepted? %>
              <%= form_with model: friendship, method: :delete do |form| %>
                <span class="badge bg-dark fs-3">Friend</span>
                <%= form.submit 'Delete friend', class: "btn btn-danger" %>
                <% end %>
              <% else %>
                <% if should_accept = friendship.friend_id == current_user.id  %>
                  <%= form_with model: friendship do |form| %>
                    <%= form.submit 'Accept request', class: "btn btn-success mb-2" %>
                  <% end %>
                <% end %>
                <%= form_with model: friendship, method: :delete do |form| %>
                  <%= form.submit (should_accept ? 'Decline request' : 'Cancel request'), class: "btn btn-danger" %>
                <% end %>
              <% end %>
            <% else %>
              <%= form_with model: Friendship.new do |form| %>
                <%= form.hidden_field :friend_id, value: user.id %>
                <%= form.submit 'Add friend', class: "btn btn-primary" %>
              <% end %>
            <% end %>
        </span>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<h1>Users directory</h1>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
  <%= render @users %>
  <div class="mx-auto"><%== pagy_bootstrap_nav(@pagy) %></div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <h1 class="text-center">Profile <%= @user.email %></h1>

  <% unless @user.id == current_user.id%>
    <div class="card-body">
        <h2>Friendship status:</h2>
        <div>
          <% if @friendship %>
            <% if @friendship.accepted? %>
            <%= form_with model: @friendship, method: :delete do |form| %>
              <span class="badge bg-dark fs-3">Friend</span>
              <%= form.submit 'Delete friend', class: "btn btn-danger" %>
              <% end %>
            <% else %>
              <% if should_accept = @friendship.friend_id == current_user.id  %>
                <%= form_with model: @friendship do |form| %>
                  <%= form.submit 'Accept request', class: "btn btn-success mb-2" %>
                <% end %>
              <% end %>
              <%= form_with model: @friendship, method: :delete do |form| %>
                <%= form.submit (should_accept ? 'Decline request' : 'Cancel request'), class: "btn btn-danger" %>
              <% end %>
            <% end %>
          <% else %>
            <%= form_with model: Friendship.new do |form| %>
              <%= form.hidden_field :friend_id, value: @user.id %>
              <%= form.submit 'Add friend', class: "btn btn-primary" %>
            <% end %>
          <% end %>
      </div>
    </div>
  <% end %>

  <h2>Information:</h2>
    <% if @user.profile.attributes.values.compact.size == 4 %>
      <p class="text-muted fst-italic">This user doesn't have edited his information yet.</p>
    <% else %>
      <ul class="list-group list-group-flush col-10 col-sm-8 col-lg-6">
        <% if @user.profile.photo.attached? %>
          <li class="list-group-item">
            <h5 class="text-decoration-underline">Profile photo:</h5>
            <%= image_tag @user.profile.photo, width: '200px' %>
          </li>
        <% end %>
        <% @user.profile.attributes.each do |attribute| %>
          <% next if attribute.first.match?(/id|_at/) || attribute.last.blank? %>

          <li class="list-group-item">
            <h5 class="text-decoration-underline"><%= attribute.first.humanize %>:</h5>
            <%= attribute.last.nil? ? '' : attribute.last.to_s.humanize %>
          </li>
        <% end %>
        <% if @user == current_user %>
          <strong><%= link_to 'Edit profile information', edit_user_profile_path(current_user.profile), class: "mt-2 ms-2 btn btn-lg btn-warning fw-bold" %></strong>
        <% end %>
      </ul>
    <% end %>

  <h2 class="text-center">Recent posts</h2>
    <% if @posts.empty?%>
      <p class="text-muted fst-italic text-center">This user doesn't have posts yet.</p>
    <% else %>
      <div><%= render @posts %></div>
    <% end %>
</div>