config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => "posts#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end
  devise_for :users
  resources :users, only: [:index, :show] do
    resource :profile, only: [:show, :edit, :update]
  end
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :show, :create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images

  validates :content, presence: true, unless: proc { |post| post.images.attached? }

  def author_and_commenters_ids
    commenters_ids = comments.distinct.pluck(:user_id)
    (commenters_ids << author.id).uniq
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  def index
    @pagy, @posts = pagy(current_user.user_and_friends_posts.includes(:author, :comments).with_attached_images, items: 8)
    @post = Post.new
    @plucked_likes_and_posts_ids_of_user_likes = current_user.likes.pluck(:id, :post_id)
  end

  def show
    @post = Post.includes(comments: :commenter).with_attached_images.find(params[:id])
    @current_user_post_like = Like.where('user_id = ? AND post_id = ?', current_user.id, params[:id]).take
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post created successfully!'
    else
      flash[:post_errors] = @post.errors.full_messages
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    @post.destroy

    redirect_to posts_path, notice: 'Post deleted successfully!', status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:content, images: [])
  end

  def set_post
    return if (@post = Post.find_by_id(params[:id]))

    redirect_to posts_path, alert: 'Sorry, post not found!', status: :see_other
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div class="row">
    <div class="col-md mb-3">
      <%= form.label :content, class: 'form-label fs-5 text-decoration-underline' %><br>
      <%= form.text_area :content, class: 'form-control' %>
        <% if flash[:post_errors] %>
          <% flash[:post_errors].each do |error| %>
            <div class="mt-2 alert alert-danger"><%= error %></div>
          <% end %>
      <% end %>
    </div>
    <div class="col-md mb-3">
      <%= form.label :images, 'Upload images:', class: 'form-label fs-5 text-decoration-underline' %>
      <%= form.file_field :images, multiple: true, class: 'form-control' %>
    </div>
  </div>
  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card col-10 col-lg-6 mx-auto mb-2">
  <div class="card-body">
    <%= link_to post.author.email, user_path(post.author), class: 'fs-4  link-primary' %>
    <% unless post.content.empty? %>
      <p class="card-text">
        <h5 class="text-decoration-underline">Content:</h5>
        <%= post.content.truncate(300) %><br>
      </p>
    <% end %>
    <% if post.images.attached? %>
      <p class="fs-5 text-decoration-underline">Images:</p>
      <% post.images.each do |image| %>
        <%= image_tag image, width: '70px' %>
      <% end %>
    <% end %>
    <%= link_to 'Read full post with comments', post_path(post), data: { turbo_frame: :_top }, class: 'btn btn-primary mb-2' %>

    <p><span class="fs-5 text-decoration-underline">Likes</span>:&nbsp;<%= post.likes_count.zero? ? 'nobody :(' : pluralize(post.likes_count, 'person') %></p>

    <% like_and_post_id = @plucked_likes_and_posts_ids_of_user_likes.find { |_like_id, post_id| post_id == post.id} %>
    <% if like_and_post_id.nil? %> 
    
      <%= button_to likes_path, params: { like: { post_id: post.id }}, method: :post, class: 'btn btn-secondary' do %>
        Like <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 14 20">
              <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
            </svg>
      <% end %>
    <% else %> 
      <%= link_to like_path(like_and_post_id), data: { turbo_frame: :_top, turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-dark' do %>
        Unlike <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-hand-thumbs-down-fill" viewBox="0 0 14 20">
                <path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
              </svg>
      <% end %>
    <% end %> <br>

    <p class="text-muted fst-italic">
      <% if post.comments.empty? %>
        This post doesn't have comments yet.
      <% else %>
        <%= pluralize(post.comments.size, 'comment') %>
      <% end %>
    </p>

    <% if post.author == current_user %>
      <%= link_to post_path(post), data: { turbo_frame: :_top, turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-sm btn-danger' do %>
            Delete post
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-recycle" viewBox="0 0 14 20">
              <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
            </svg>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="card my-2 border-top-0">
  <div class="card-body">
    <h5 class="card-title">What are you thinking? <span class="card-subtitle mb-2 text-muted">Create a New Post</span></h5>
    
    <%= render 'form', post: @post %>
  </div>
</div>

<h1 class="text-center">Recent posts</h1>
<% if @posts.empty?%>
  <p class="text-muted fst-italic text-center">This user doesn't have posts yet.</p>
<% else %>
  <div>
    <!-- Using Turbo Frames for posts pagination -->
    <%= turbo_frame_tag "recent-posts", autoscroll: "true" do %>
      <div class="sticky-top"><%== pagy_bootstrap_nav(@pagy, link_extra: 'data-turbo-action="advance"' ) %></div>
      <%= render @posts %>
    <% end %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container-fluid">
  <h2><%= @post.author.email %> published:</h2>
  <% unless @post.content.empty? %>
    <p class="fs-5 card p-2"><%= @post.content %></p>
  <% end %>

  <% if @post.images.attached? %>
    <p class="fs-5 text-decoration-underline">Images:</p>
    <% @post.images.each do |image| %>
      <%= image_tag image, width: '300px' %>
    <% end %>
  <% end %>
  <p>
    <span class="fs-5 text-decoration-underline">Likes</span>:&nbsp;
    <%= @post.likes_count.zero? ? 'nobody :(' : pluralize(@post.likes_count, 'person') %>
  </p>

  <% if @current_user_post_like.nil? %> 
    <%= button_to likes_path, params: { like: { post_id: @post.id }}, method: :post, class: 'btn btn-secondary' do %>
      Like <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 14 20">
                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
              </svg>
        <% end %>
  <% else %> 
    <%= button_to like_path(@current_user_post_like), method: :delete, class: 'btn btn-dark' do %>
      Unlike <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-hand-thumbs-down-fill" viewBox="0 0 14 20">
                  <path d="M6.956 14.534c.065.936.952 1.659 1.908 1.42l.261-.065a1.378 1.378 0 0 0 1.012-.965c.22-.816.533-2.512.062-4.51.136.02.285.037.443.051.713.065 1.669.071 2.516-.211.518-.173.994-.68 1.2-1.272a1.896 1.896 0 0 0-.234-1.734c.058-.118.103-.242.138-.362.077-.27.113-.568.113-.856 0-.29-.036-.586-.113-.857a2.094 2.094 0 0 0-.16-.403c.169-.387.107-.82-.003-1.149a3.162 3.162 0 0 0-.488-.9c.054-.153.076-.313.076-.465a1.86 1.86 0 0 0-.253-.912C13.1.757 12.437.28 11.5.28H8c-.605 0-1.07.08-1.466.217a4.823 4.823 0 0 0-.97.485l-.048.029c-.504.308-.999.61-2.068.723C2.682 1.815 2 2.434 2 3.279v4c0 .851.685 1.433 1.357 1.616.849.232 1.574.787 2.132 1.41.56.626.914 1.28 1.039 1.638.199.575.356 1.54.428 2.591z"/>
                </svg>
        <% end %>
  <% end %>

  <% if @post.author == current_user %>
    <h6 class="mt-3">Unhappy with this post?</h6>
    <%= button_to post_path(@post), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'btn btn-sm btn-danger' do %>
    Delete post <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-recycle" viewBox="0 0 14 20">
                        <path d="M9.302 1.256a1.5 1.5 0 0 0-2.604 0l-1.704 2.98a.5.5 0 0 0 .869.497l1.703-2.981a.5.5 0 0 1 .868 0l2.54 4.444-1.256-.337a.5.5 0 1 0-.26.966l2.415.647a.5.5 0 0 0 .613-.353l.647-2.415a.5.5 0 1 0-.966-.259l-.333 1.242-2.532-4.431zM2.973 7.773l-1.255.337a.5.5 0 1 1-.26-.966l2.416-.647a.5.5 0 0 1 .612.353l.647 2.415a.5.5 0 0 1-.966.259l-.333-1.242-2.545 4.454a.5.5 0 0 0 .434.748H5a.5.5 0 0 1 0 1H1.723A1.5 1.5 0 0 1 .421 12.24l2.552-4.467zm10.89 1.463a.5.5 0 1 0-.868.496l1.716 3.004a.5.5 0 0 1-.434.748h-5.57l.647-.646a.5.5 0 1 0-.708-.707l-1.5 1.5a.498.498 0 0 0 0 .707l1.5 1.5a.5.5 0 1 0 .708-.707l-.647-.647h5.57a1.5 1.5 0 0 0 1.302-2.244l-1.716-3.004z"/>
                      </svg>
    <% end %> 
  <% end %>

  <h3 class="mt-3">Comments:</h3>
  <% if @post.comments.empty? %>
    <p class="text-muted fst-italic">This post doesn't have comments yet.</p>
    <p class="fst-italic">You can be the first!</p>
  <% else %>
    <div class="ms-3 col-10 col-sm-8"><%= render @post.comments %></div>
  <% end %>

  <%= render 'comments/form', post: @post %>
</div>